### ISSUE TITLE
CRAN failure

### ISSUE THREAD

**Issue by hadley** [rstudio/bigD#14]
Unfortunately the recent waldo release broke your package on CRAN because it no longer imports tibble, and your package was implicitly depending on it. The easiest fix is to just make the dependency explicit, by adding tibble to Suggests.

Many apologies for the hassle. Unfortunately we didn't discover this prior to CRAN release because we had a bug in the code that runs our revdep checks 🙁.

**Comment by rich-iannone** [comment]
This is not a problem at all. I'll make the change and submit to CRAN!

**Comment by rich-iannone** [comment]
The updated package is now on CRAN.
